#!/usr/bin/env python
"""
"""
from dispatcher import CommandDispatcher
from command import Command


class HodorCommand(Command):
    """
    """
    _command = 'hodor'
    _description = 'this is the hodor command'
    _hide = False

    def __call__(self):
        print('Hodor! Hodor! Hodor!')


class GrootCommand(Command):
    """
    """
    _command = 'groot'
    _description = 'This is the groot command'
    _hide = False

    def __call__(self):
        print('I am Groot! I am Groot! I am Groot!')



class MyDispatcher(CommandDispatcher):
    """
    """
    _cmd = __file__
    _name = 'Mega Commander'
    _default_commands = [HodorCommand, GrootCommand]



if __name__ == '__main__':
    dispatcher = MyDispatcher()
